spring:
  application:
    name: springweb-example
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:example}
    password: ${POSTGRES_PASSWORD:example}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:example}
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: ${SERVER_PORT:9001}