apiVersion: apps/v1
kind: Deployment
metadata:
  name: springweb-jpa-example
  labels:
    app: springweb-jpa-example
    tier: backend
    env: development
    version: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springweb-jpa-example
      tier: backend
      env: development
      version: stable
  template:
    metadata:
      name: springweb-jpa-example
      labels:
        app: springweb-jpa-example
        tier: backend
        env: development
        version: stable
    spec:
      containers:
        - name: springweb-jpa-example
          image: dimmaryanto93/spring-k8s-signoz:springweb-jpa
          command: [ "java","-javaagent:/usr/share/applications/opentelemetry-javaagent.jar" , "-jar", "-Djava.security.egd=file:/dev/./urandom", "spring-boot.jar" ]
          args: [ ]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: springweb-jpa-example
                optional: false
            - secretRef:
                name: signoz-cred
                optional: false
            - secretRef:
                name: db-cred
                optional: false
      restartPolicy: Always
