apiVersion: v1
kind: Secret
metadata:
  name: signoz-cred
stringData:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://10.12.10.45:4317"
  OTEL_TRACES_EXPORTER: "otlp"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-cred
stringData:
  POSTGRES_HOST: "10.12.11.84"
  POSTGRES_PORT: "5432"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB_NAME: "example"