apiVersion: v1
kind: Secret
metadata:
  name: signoz-cred
stringData:
  OTEL_EXPORTER_OTLP_HEADERS: "signoz-access-token=SIGNOZ_INGESTION_KEY"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://ingest.{region}.signoz.cloud:443"