apiVersion: v1
kind: Secret
metadata:
  name: signoz-cred
stringData:
#  OTEL_EXPORTER_OTLP_HEADERS: "signoz-access-token=SIGNOZ_INGESTION_KEY"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://10.12.10.45:4317"
  OTEL_TRACES_EXPORTER: "otlp"