apiVersion: v1
kind: Service
metadata:
  name: springweb-example
spec:
  selector:
    app: springweb-example
    tier: backend
    env: development
    version: stable
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort